#!/usr/bin/env python3

import sys
import estat as ef

if __name__ == "__main__":

    if len(sys.argv) < 2:
        print("Please provide a function to execute. Usage: 'estat [function] ...'")
        sys.exit(1)

    function_name = sys.argv[1]
    arguments = sys.argv[2:]  # Get the rest of the arguments

    # Convert arguments to appropriate data types
    if function_name == 'plot':
        arguments[2] = int(arguments[2])  # Convert col to integer
        arguments[3] = int(arguments[3])  # Convert t to integer

    # Execute the function with the provided arguments
    if function_name == 'search':
        result = ef.search(*arguments)
        print(result)
    elif function_name == 'show_geos':
        result = ef.show_geos(*arguments)
        print(result)
    elif function_name == 'show':
        result = ef.show(*arguments)
        print(result)
    elif function_name == 'plot':
        ef.plot(*arguments)
    else:
        print(f"Unknown function: {function_name}")
